# Generated by Django 4.2.6 on 2023-11-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followforeign',
            name='following',
            field=models.UUIDField(),
        ),
    ]
