# Generated by Django 4.2.6 on 2023-11-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_followforeign_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='comment',
            new_name='object',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='like_comment',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='like_post',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post',
        ),
    ]
