# Generated by Django 4.2.6 on 2023-11-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foreign_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
