# Generated by Django 4.2.6 on 2023-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comment_inbox_object_remove_inbox_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='actor',
            field=models.UUIDField(),
        ),
    ]
