# Generated by Django 4.2.6 on 2023-11-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_postaccesspermissionforeign_author_follow_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='followforeign',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='followforeign',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postaccesspermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postaccesspermission',
            name='author_follow_relation',
        ),
        migrations.RemoveField(
            model_name='postaccesspermission',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postaccesspermission',
            name='target_follow_relation',
        ),
        migrations.RemoveField(
            model_name='postaccesspermission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postaccesspermissionforeign',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postaccesspermissionforeign',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='user',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowForeign',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PostAccessPermission',
        ),
        migrations.DeleteModel(
            name='PostAccessPermissionForeign',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('target', 'follower')},
        ),
    ]
