# Generated by Django 4.2.6 on 2023-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_inboxitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('comment', 'comment'), ('post', 'post'), ('Like', 'Like')], max_length=50),
        ),
    ]
