# Generated by Django 4.2.6 on 2023-11-25 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_inboxitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
