# Generated by Django 4.2.6 on 2023-11-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_comment_is_private_alter_likecomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.post')),
            ],
            bases=('api.post',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_shared',
        ),
    ]
