# Generated by Django 4.2.6 on 2023-11-25 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sharedpost_remove_post_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='receiver',
            field=models.ForeignKey(default='465f0c29-690e-4960-96b4-98341eb29fca', on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
