# Generated by Django 4.2.6 on 2023-11-25 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sharedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedPost',
        ),
    ]
