# Generated by Django 4.2.6 on 2023-11-25 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_post_receiver_delete_sharedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='receiver',
        ),
        migrations.AddField(
            model_name='post',
            name='is_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_access', to='api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
