# Generated by Django 4.2.6 on 2023-11-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_follow_target_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
